### ISSUE TITLE
GrabFX issue with left hand

### ISSUE THREAD

**Issue by ZeichenZwerg** [VRLabs/VRChat-Avatars-3.0#2]
Hello,
i tried to apply the grabFX today to a avatar. I tried it like 5 - 6 times, each time with a fresh project and i think the left hand grabbing is broken. Followed the instructions on point, right hand works perfectly fine but the left hand can't grab. Also used the Avatar 3.0 Manager as well as the Fix Order tool. As you can see on the screenshot from the debug menu the LeftGrabFX is stuck at "10" right after spawning/resetting avatar. Also the onLeftGrab is constantly at "LeftGrabFX to 10". Also i only use 1 of the grab elements and in the controller the value on which it should set the layer looks fine.

![Debug](https://user-images.githubusercontent.com/84046749/118012315-34884200-b351-11eb-9662-3ec245fcd064.png)
![Unity](https://user-images.githubusercontent.com/84046749/118013632-9bf2c180-b352-11eb-8205-faecf0221b13.png)

**Comment by ksivl** [comment]
You are missing a Base Layer in your FX Controller as the 0th (first) layer, whose weight cannot be changed from 1.0 by the VRC Animator Layer Control (see https://docs.vrchat.com/docs/state-behaviors#animator-layer-controller). Consequently, the layer ʟᴇғᴛɢʀᴀʙ is the first layer and defaults to a weight of 1.0, constantly driving LeftGrabFX to 10.

Your solution should be to simply add an empty layer to your FX controller and position it as the 0th (first) layer, so that ʟᴇғᴛɢʀᴀʙ's layer index is nonzero and its weight can be successfully driven by the Animator Layer Control. Then, rerun Fix Order.
